<?php
require_once __DIR__ . '/config.php';

$allFlags = ['germany'=>'🇩🇪','usa'=>'🇺🇸','turkey'=>'🇹🇷','sweden'=>'🇸🇪','azerbaijan'=>'🇦🇿','netherlands'=>'🇳🇱','france'=>'🇫🇷','uk'=>'🇬🇧','canada'=>'🇨🇦','spain'=>'🇪🇸','italy'=>'🇮🇹','japan'=>'🇯🇵','singapore'=>'🇸🇬','uae'=>'🇦🇪','russia'=>'🇷🇺','switzerland'=>'🇨🇭','poland'=>'🇵🇱','finland'=>'🇫🇮','norway'=>'🇳🇴','denmark'=>'🇩🇰','austria'=>'🇦🇹','belgium'=>'🇧🇪','portugal'=>'🇵🇹','brazil'=>'🇧🇷','india'=>'🇮🇳','australia'=>'🇦🇺','south_korea'=>'🇰🇷','romania'=>'🇷🇴','ukraine'=>'🇺🇦','czech'=>'🇨🇿'];

$isLoggedIn = false; $adminFile = __DIR__ . '/data/admin.json';
if (isset($_POST['email']) && isset($_POST['password'])) { if (file_exists($adminFile)) { $adminData = json_decode(file_get_contents($adminFile), true); if ($adminData && $adminData['email'] === $_POST['email'] && password_verify($_POST['password'], $adminData['password'])) { $_SESSION['admin_logged_in'] = true; $_SESSION['admin_email'] = $adminData['email']; $_SESSION['admin_login_time'] = time(); } } }
if (isset($_GET['logout'])) { session_destroy(); header('Location: /admin'); exit; }
if (isset($_SESSION['admin_login_time']) && (time() - $_SESSION['admin_login_time'] > 28800)) { session_destroy(); header('Location: /admin'); exit; }
$isLoggedIn = isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'];
if (!isset($_SESSION['csrf_token'])) { $_SESSION['csrf_token'] = bin2hex(random_bytes(32)); }

$message = ''; $messageType = 'success';
$settings = loadSettings(); $servers = loadServers(); $allUsers = loadUsers();
$testConfigs = $settings['test_configs'] ?? [];

if ($isLoggedIn) {
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['csrf_token'])) { if ($_POST['csrf_token'] !== $_SESSION['csrf_token']) die('CSRF'); }
    
    if (isset($_POST['save_panel'])) {
        $c = file_get_contents(__DIR__.'/config.php');
        $c = preg_replace("/define\('PANEL_URL',\s*'[^']*'\);/","define('PANEL_URL', '".addslashes($_POST['panel_url'])."');",$c);
        $c = preg_replace("/define\('PANEL_TOKEN',\s*'[^']*'\);/","define('PANEL_TOKEN', '".addslashes($_POST['panel_token'])."');",$c);
        $c = preg_replace("/define\('MERCHANT_ID',\s*'[^']*'\);/","define('MERCHANT_ID', '".addslashes($_POST['merchant_id'])."');",$c);
        file_put_contents(__DIR__.'/config.php',$c); $message='Config updated.'; $messageType='success';
    }
    if (isset($_POST['save_settings'])) { $settings['card_number']=trim($_POST['card_number']??'');$settings['card_holder']=trim($_POST['card_holder']??'');$settings['card_bank']=trim($_POST['card_bank']??'');$settings['zarinpal_enabled']=isset($_POST['zarinpal_enabled']);$settings['card_enabled']=isset($_POST['card_enabled']);saveSettings($settings);$message='Settings saved.';$messageType='success'; }
    if (isset($_POST['save_servers'])) { $newServers=[];$snames=$_POST['server_name']??[];$scodes=$_POST['server_code']??[];$sinbounds=$_POST['server_inbounds']??[];$sflags=$_POST['server_flag']??[];foreach($snames as $i=>$name){$name=trim($name);$code=trim($scodes[$i]??'');$ib=trim($sinbounds[$i]??'');$flag=trim($sflags[$i]??'🌍');if(!empty($name)&&!empty($code)&&!empty($ib)){$inbounds=array_values(array_filter(array_map('intval',explode(',',$ib))));if(!empty($inbounds))$newServers[]=['location'=>$code,'location_name'=>$name,'location_emoji'=>$flag,'inbounds'=>$inbounds];}}saveServers($newServers);$servers=$newServers;$message='Servers saved.';$messageType='success';}
    
    // SAVE TESTS - simple and clean
    if (isset($_POST['save_tests'])) {
        $newConfigs = [];
        $srv = $_POST['test_server'] ?? [];
        $vol = $_POST['test_volume'] ?? [];
        $unt = $_POST['test_unit'] ?? [];
        $hrs = $_POST['test_hours'] ?? [];
        $mul = $_POST['test_multi'] ?? [];
        $cnt = max(count($srv), count($vol), count($unt), count($hrs));
        for ($i = 0; $i < $cnt; $i++) {
            $isMulti = isset($mul[$i]) && $mul[$i] == '1';
            $server = trim($srv[$i] ?? '');
            $volume = max(0.1, (float)($vol[$i] ?? 1));
            $unit = ($unt[$i] ?? 'GB') === 'MB' ? 'MB' : 'GB';
            $hours = max(1, (int)($hrs[$i] ?? 2));
            if ($isMulti) {
                $allCodes = []; foreach ($servers as $s) { $allCodes[] = $s['location']; }
                $newConfigs[] = ['server'=>'multi','servers'=>$allCodes,'volume'=>$volume,'unit'=>$unit,'hours'=>$hours,'multi'=>true];
            } else {
                $newConfigs[] = ['server'=>$server,'volume'=>$volume,'unit'=>$unit,'hours'=>$hours];
            }
        }
        $settings['test_configs'] = $newConfigs;
        saveSettings($settings);
        $testConfigs = $newConfigs;
        $message = 'Tests saved (' . count($newConfigs) . ' configs).'; $messageType = 'success';
    }
    
    if (isset($_POST['add_plan'])) { $plans=loadPlans();$isMulti=isset($_POST['is_multi']);if($isMulti){$ai=[];$ln=[];$le=[];$sl=[];foreach($servers as $s){$ai=array_merge($ai,$s['inbounds']);$ln[]=$s['location_name'];$le[]=$s['location_emoji'];$sl[]=$s['location'];}$ai=array_values(array_unique($ai));$np=['id'=>'plan_'.time().'_'.bin2hex(random_bytes(4)),'name'=>trim($_POST['name']??''),'location'=>'multi','locations'=>$sl,'location_name'=>'Multi','location_emoji'=>implode(' ',$le),'volume'=>max(1,(int)($_POST['volume']??0)),'days'=>max(1,(int)($_POST['days']??0)),'price'=>max(1000,(int)($_POST['price']??0)),'inbounds'=>$ai,'active'=>true,'featured'=>isset($_POST['featured']),'created_at'=>date('Y-m-d H:i:s'),'multi_location'=>true];$plans[]=$np;savePlans($plans);$message='Plan added.';$messageType='success';}else{$loc=trim($_POST['location']??'');if(empty($loc)){$message='Select country.';$messageType='error';}else{$svr=null;foreach($servers as $s){if($s['location']===$loc){$svr=$s;break;}}$np=['id'=>'plan_'.time().'_'.bin2hex(random_bytes(4)),'name'=>trim($_POST['name']??''),'location'=>$loc,'location_name'=>$svr['location_name']??$loc,'location_emoji'=>$svr['location_emoji']??'🌍','volume'=>max(1,(int)($_POST['volume']??0)),'days'=>max(1,(int)($_POST['days']??0)),'price'=>max(1000,(int)($_POST['price']??0)),'inbounds'=>$svr['inbounds']??ALL_INBOUNDS,'active'=>true,'featured'=>isset($_POST['featured']),'created_at'=>date('Y-m-d H:i:s')];$plans[]=$np;savePlans($plans);$message='Plan added.';$messageType='success';}}}
    if (isset($_POST['edit_plan'])) { $plans=loadPlans();$eid=$_POST['plan_id']??'';foreach($plans as &$p){if($p['id']===$eid){$isMulti=isset($_POST['is_multi']);if($isMulti){$ai=[];$ln=[];$le=[];$sl=[];foreach($servers as $s){$ai=array_merge($ai,$s['inbounds']);$ln[]=$s['location_name'];$le[]=$s['location_emoji'];$sl[]=$s['location'];}$ai=array_values(array_unique($ai));$p['location']='multi';$p['locations']=$sl;$p['location_name']='Multi';$p['location_emoji']=implode(' ',$le);$p['inbounds']=$ai;$p['multi_location']=true;}else{$loc=trim($_POST['location']??$p['location']);$svr=null;foreach($servers as $s){if($s['location']===$loc){$svr=$s;break;}}if($svr){$p['location']=$loc;$p['location_name']=$svr['location_name'];$p['location_emoji']=$svr['location_emoji'];$p['inbounds']=$svr['inbounds'];$p['multi_location']=false;}}$p['name']=trim($_POST['name']??$p['name']);$p['volume']=max(1,(int)($_POST['volume']??$p['volume']));$p['days']=max(1,(int)($_POST['days']??$p['days']));$p['price']=max(1000,(int)($_POST['price']??$p['price']));$p['featured']=isset($_POST['featured']);$p['updated_at']=date('Y-m-d H:i:s');$message='Plan updated.';$messageType='success';break;}}savePlans($plans);}
    if(isset($_GET['delete'])&&isset($_GET['confirm'])){$plans=loadPlans();$plans=array_values(array_filter($plans,fn($p)=>$p['id']!==$_GET['delete']));savePlans($plans);header('Location: /admin?tab=plans');exit;}
    if(isset($_GET['toggle'])){$plans=loadPlans();foreach($plans as &$p){if($p['id']===$_GET['toggle']){$p['active']=!($p['active']??true);break;}}savePlans($plans);header('Location: /admin?tab=plans');exit;}
    if(isset($_GET['duplicate'])){$plans=loadPlans();foreach($plans as $p){if($p['id']===$_GET['duplicate']){$np=$p;$np['id']='plan_'.time().'_'.bin2hex(random_bytes(4));$np['name']=$p['name'].' (Copy)';$np['created_at']=date('Y-m-d H:i:s');unset($np['updated_at']);$plans[]=$np;break;}}savePlans($plans);header('Location: /admin?tab=plans');exit;}
    if(isset($_GET['delete_server'])){$servers=loadServers();$servers=array_values(array_filter($servers,fn($s)=>$s['location']!==$_GET['delete_server']));saveServers($servers);header('Location: /admin?tab=servers');exit;}
    if(isset($_POST['reset_stats'])&&$_POST['reset_stats']==='CONFIRM'){saveOrders([]);savePending([]);header('Location: /admin?tab=reset');exit;}
}

$plans=loadPlans();$orders=loadOrders();$allUsers=loadUsers();$pp=loadPending();
$pendingList=array_filter($pp,fn($p)=>($p['status']??'')==='pending');
$tr=array_sum(array_column($orders,'amount'));$ap=count(array_filter($plans,fn($p)=>$p['active']??true));
$tp=count($plans);$to=count($orders);$pc=count($pendingList);$ts=count($servers);$tu=count($allUsers);
$activeTab = $_GET['tab'] ?? 'dashboard';
$testConfigs = $settings['test_configs'] ?? [];
$today = date('Y-m-d');
$todayUsers = count(array_filter($allUsers, fn($u) => strpos($u['created_at']??'', $today) === 0));
$todayOrders = count(array_filter($orders, fn($o) => strpos($o['date']??'', $today) === 0));
$todayRevenue = array_sum(array_column(array_filter($orders, fn($o) => strpos($o['date']??'', $today) === 0), 'amount'));
$testUsers = file_exists(__DIR__.'/data/test_users.json') ? json_decode(file_get_contents(__DIR__.'/data/test_users.json'), true) : [];
$todayTests = count(array_filter($testUsers, fn($t) => strpos($t['time']??'', $today) === 0));
?><!DOCTYPE html><html lang="en" dir="ltr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Admin | AlexVPN</title><meta name="robots" content="noindex"><link rel="icon" href="/alexvpn.png"><meta name="theme-color" content="#060a1a">
<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap');
:root{--bg:#050914;--card:rgba(11,15,36,0.85);--border:rgba(255,255,255,0.06);--border2:rgba(255,255,255,0.12);--text:#e4e4f0;--text2:#b0b0cc;--text3:#707090;--p1:#7c6ff7;--t1:#00d4cc;--a1:#ff6b9d;--w1:#fdcb6e;--grad1:linear-gradient(135deg,#7c6ff7,#5b4fcf);--grad3:linear-gradient(135deg,#ff6b9d,#e85d75);--grad4:linear-gradient(135deg,#00b894,#00d4cc);--trans:0.25s ease}*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;line-height:1.6}
.login-wrap{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.login-card{background:var(--card);border:1px solid var(--border2);border-radius:24px;padding:40px 28px;width:100%;max-width:400px;backdrop-filter:blur(40px);box-shadow:0 20px 50px rgba(0,0,0,0.5);text-align:center}.login-card img{width:52px;height:52px;margin-bottom:14px}.login-card h1{font-weight:900;font-size:1.3rem}.login-card input{width:100%;padding:13px 16px;border-radius:12px;border:2px solid var(--border2);background:rgba(255,255,255,0.02);color:#fff;font-family:inherit;font-size:.9rem;margin-bottom:10px;transition:var(--trans);outline:none}.login-card input:focus{border-color:var(--p1)}
.admin-wrap{max-width:1400px;margin:0 auto;padding:0 16px}.admin-header{position:sticky;top:0;z-index:100;backdrop-filter:blur(40px);background:rgba(5,9,20,0.8);border-bottom:1px solid var(--border);padding:10px 0;margin-bottom:20px}.admin-header .inner{max-width:1400px;margin:0 auto;padding:0 16px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px}
.btn{display:inline-flex;align-items:center;gap:6px;padding:8px 16px;border-radius:32px;font-weight:700;font-size:.76rem;text-decoration:none;border:none;cursor:pointer;transition:var(--trans);font-family:inherit;white-space:nowrap}.btn-primary{background:var(--grad1);color:#fff}.btn-success{background:var(--grad4);color:#fff}.btn-danger{background:var(--grad3);color:#fff}.btn-outline{background:transparent;border:1px solid var(--border2);color:var(--text2)}.btn-xs{padding:4px 10px;font-size:.64rem;border-radius:14px}.btn-sm{padding:6px 12px;font-size:.7rem}
.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin-bottom:20px}.stat-card{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:18px 14px}.stat-card .v{font-size:1.5rem;font-weight:900}.stat-card .l{color:var(--text3);font-size:.62rem;text-transform:uppercase}
.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px}.chart-card{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:20px}.chart-card h4{color:var(--t1);font-size:.78rem;text-transform:uppercase;margin-bottom:12px}.bar{height:8px;background:rgba(255,255,255,0.05);border-radius:4px;margin:6px 0;overflow:hidden}.bar-fill{height:100%;border-radius:4px;background:var(--grad1)}.bar-label{display:flex;justify-content:space-between;font-size:.68rem;color:var(--text3)}
.card{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:20px;backdrop-filter:blur(20px);margin-bottom:16px}.tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:16px}.tab-btn{padding:8px 14px;border-radius:22px;background:transparent;color:var(--text2);border:1px solid var(--border);cursor:pointer;font-family:inherit;font-size:.7rem;font-weight:600;transition:var(--trans);white-space:nowrap;text-transform:uppercase;text-decoration:none;display:inline-flex;align-items:center}.tab-btn:hover{border-color:rgba(255,255,255,0.18);color:#fff}.tab-btn.active{background:rgba(124,111,247,0.12);border-color:var(--p1);color:#fff}.tab-content{display:none}.tab-content.active{display:block;animation:fadeIn .3s ease}@keyframes fadeIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form-group{margin-bottom:12px}.form-group label{display:block;margin-bottom:4px;color:var(--text2);font-size:.72rem;font-weight:600;text-transform:uppercase}.form-group input,.form-group select{width:100%;padding:9px 12px;border-radius:10px;border:2px solid var(--border2);background:#0b0f24;color:#fff;font-family:inherit;font-size:.8rem;outline:none}.form-group select option{background:#0b0f24;color:#fff}
table{width:100%;border-collapse:collapse;font-size:.72rem}th{color:var(--t1);font-weight:700;padding:10px 8px;text-align:left;border-bottom:2px solid var(--border);text-transform:uppercase;font-size:.63rem}td{padding:10px 8px;border-bottom:1px solid rgba(255,255,255,0.03)}.badge{padding:3px 9px;border-radius:14px;font-size:.58rem;font-weight:700;text-transform:uppercase}.badge-success{background:rgba(0,212,204,0.1);color:var(--t1)}.badge-danger{background:rgba(255,107,157,0.1);color:var(--a1)}
.server-row,.test-row{display:flex;align-items:center;gap:8px;margin-bottom:8px;background:rgba(0,0,0,0.25);padding:10px 12px;border-radius:14px;flex-wrap:wrap}.server-row select,.server-row input,.test-row select,.test-row input{flex:1;min-width:50px;padding:8px 10px;border-radius:10px;border:2px solid var(--border2);background:#0b0f24;color:#fff;font-family:inherit;font-size:.76rem;outline:none}.flag-select{font-size:1.4rem!important;text-align:center;max-width:60px!important;flex:0 0 60px!important}.test-row .multi-check{display:flex;align-items:center;gap:4px;color:var(--t1);font-size:.66rem;white-space:nowrap;min-width:55px}
.modal-overlay{position:fixed;top:0;left:0;width:100%;height:100%;z-index:200;background:rgba(0,0,0,0.7);backdrop-filter:blur(8px);display:flex;align-items:center;justify-content:center;padding:20px}.modal{background:#0b0f24;border:1px solid var(--border2);border-radius:20px;padding:26px 22px;max-width:500px;width:100%;box-shadow:0 30px 60px rgba(0,0,0,0.6);position:relative}.modal h3{font-size:1.1rem;font-weight:900;margin-bottom:14px;text-align:center}.modal .close-btn{position:absolute;top:10px;right:12px;background:none;border:none;color:var(--text3);font-size:1.2rem;cursor:pointer}
.alert{padding:10px 16px;border-radius:12px;margin-bottom:16px;font-size:.78rem;font-weight:600;animation:alertIn .3s ease,alertOut .3s ease 2.5s forwards}@keyframes alertIn{from{opacity:0;transform:translateY(-10px)}to{opacity:1;transform:translateY(0)}}@keyframes alertOut{from{opacity:1}to{opacity:0;transform:translateY(-10px)}}.alert-success{background:rgba(0,212,204,0.08);border:1px solid rgba(0,212,204,0.2);color:var(--t1)}.alert-error{background:rgba(255,107,157,0.08);color:var(--a1)}
@media(max-width:768px){.form-grid{grid-template-columns:1fr}.chart-grid{grid-template-columns:1fr}.server-row,.test-row{flex-direction:column}.tabs{overflow-x:auto;flex-wrap:nowrap;padding-bottom:4px}}
</style></head><body>
<?php if(!$isLoggedIn): ?><div class="login-wrap"><div class="login-card"><img src="/alexvpn.png"><h1>Admin Panel</h1><form method="post"><input type="email" name="email" placeholder="Email" required><input type="password" name="password" placeholder="Password" required><button type="submit" class="btn btn-primary" style="width:100%;">Login</button></form><?php if(!file_exists($adminFile)): ?><p style="margin-top:12px;font-size:.78rem;"><a href="/install.php" style="color:var(--t1);">Setup</a></p><?php endif; ?></div></div>
<?php else: ?>
<div class="admin-header"><div class="inner"><span style="font-weight:900;font-size:1rem;">AlexVPN Admin</span><div style="display:flex;gap:6px;align-items:center;"><span style="color:var(--text3);font-size:.7rem;"><?php echo $_SESSION['admin_email']??''; ?></span><a href="<?php echo SITE_URL; ?>/" class="btn btn-outline btn-sm" target="_blank">Site</a><a href="?logout=1" class="btn btn-danger btn-sm">Logout</a></div></div></div>
<div class="admin-wrap">
<?php if($message): ?><div class="alert alert-<?php echo $messageType; ?>" id="autoAlert"><?php echo $message; ?></div><?php endif; ?>
<div class="stats-grid"><div class="stat-card"><div class="v"><?php echo $tu; ?></div><div class="l">Users</div></div><div class="stat-card"><div class="v"><?php echo $tp; ?></div><div class="l">Plans</div></div><div class="stat-card"><div class="v"><?php echo $to; ?></div><div class="l">Orders</div></div><div class="stat-card"><div class="v"><?php echo number_format($tr); ?></div><div class="l">Revenue</div></div><div class="stat-card"><div class="v" style="color:<?php echo $pc>0?'var(--w1)':'var(--t1)'; ?>"><?php echo $pc; ?></div><div class="l">Pending</div></div><div class="stat-card"><div class="v"><?php echo $ts; ?></div><div class="l">Servers</div></div></div>
<div class="tabs">
    <a href="?tab=dashboard" class="tab-btn <?php echo $activeTab==='dashboard'?'active':''; ?>">Dashboard</a>
    <a href="?tab=plans" class="tab-btn <?php echo $activeTab==='plans'?'active':''; ?>">Plans</a>
    <a href="?tab=add" class="tab-btn <?php echo $activeTab==='add'?'active':''; ?>">+ Add</a>
    <a href="?tab=pending" class="tab-btn <?php echo $activeTab==='pending'?'active':''; ?>">Pending</a>
    <a href="?tab=servers" class="tab-btn <?php echo $activeTab==='servers'?'active':''; ?>">Servers</a>
    <a href="?tab=tests" class="tab-btn <?php echo $activeTab==='tests'?'active':''; ?>">Tests</a>
    <a href="?tab=users" class="tab-btn <?php echo $activeTab==='users'?'active':''; ?>">Users</a>
    <a href="?tab=settings" class="tab-btn <?php echo $activeTab==='settings'?'active':''; ?>">Settings</a>
    <a href="?tab=orders" class="tab-btn <?php echo $activeTab==='orders'?'active':''; ?>">Orders</a>
    <a href="?tab=panel" class="tab-btn <?php echo $activeTab==='panel'?'active':''; ?>" style="border-color:rgba(253,203,110,0.3);color:#fdcb6e">Panel</a>
    <a href="?tab=reset" class="tab-btn <?php echo $activeTab==='reset'?'active':''; ?>" style="color:var(--a1);">Reset</a>
</div>

<?php if($activeTab==='dashboard'): ?><div class="tab-content active"><div class="chart-grid">
    <div class="chart-card"><h4>Today</h4>
        <div class="bar-label"><span>Users (<?php echo $todayUsers; ?>)</span><span><?php echo $tu>0?round($todayUsers/$tu*100):0; ?>%</span></div><div class="bar"><div class="bar-fill" style="width:<?php echo $tu>0?round($todayUsers/$tu*100):0; ?>%"></div></div>
        <div class="bar-label"><span>Orders (<?php echo $todayOrders; ?>)</span><span><?php echo $to>0?round($todayOrders/$to*100):0; ?>%</span></div><div class="bar"><div class="bar-fill" style="width:<?php echo $to>0?round($todayOrders/$to*100):0; ?>%;background:var(--grad4)"></div></div>
        <div class="bar-label"><span>Revenue</span><span><?php echo number_format($todayRevenue); ?> T</span></div><div class="bar"><div class="bar-fill" style="width:<?php echo $tr>0?round($todayRevenue/$tr*100):0; ?>%;background:linear-gradient(135deg,#fdcb6e,#f39c12)"></div></div>
        <div class="bar-label"><span>Tests</span><span><?php echo $todayTests; ?></span></div><div class="bar"><div class="bar-fill" style="width:<?php echo min($todayTests*20,100); ?>%;background:linear-gradient(135deg,#ff6b9d,#e85d75)"></div></div>
    </div>
    <div class="chart-card"><h4>Recent Users</h4>
        <?php $ru = array_filter($allUsers, fn($u) => strpos($u['created_at']??'', $today) === 0); if(empty($ru)): ?><p style="color:var(--text3);font-size:.72rem;padding:10px">No new users</p>
        <?php else: foreach(array_reverse($ru) as $u): ?><div style="display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid rgba(255,255,255,0.03);font-size:.7rem"><span><?php echo htmlspecialchars($u['name']??$u['email']); ?></span><span style="color:var(--text3)"><?php echo htmlspecialchars($u['email']); ?></span></div><?php endforeach; endif; ?>
    </div>
</div></div><?php endif; ?>

<?php if($activeTab==='plans'): ?><div class="tab-content active"><div class="card"><?php if(empty($plans)): ?><p style="text-align:center;color:var(--text3);padding:30px;">No plans.</p><?php else: ?><div style="overflow-x:auto;"><table><thead><tr><th>Name</th><th>Location</th><th>Vol</th><th>Days</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($plans as $p): ?><tr><td><strong><?php echo htmlspecialchars($p['name']); ?></strong> <?php echo ($p['featured']??false)?'⭐':''; ?></td><td><?php echo htmlspecialchars($p['location_emoji']??'🌍'); ?> <?php echo htmlspecialchars($p['location_name']??''); ?></td><td><?php echo (int)$p['volume']; ?> GB</td><td><?php echo (int)$p['days']; ?></td><td><strong><?php echo number_format((int)$p['price']); ?></strong></td><td><span class="badge <?php echo ($p['active']??true)?'badge-success':'badge-danger'; ?>"><?php echo ($p['active']??true)?'Active':'Inactive'; ?></span></td><td><div style="display:flex;gap:4px;"><button class="btn btn-outline btn-xs" onclick="editPlan('<?php echo $p['id']; ?>','<?php echo htmlspecialchars(addslashes($p['name'])); ?>','<?php echo $p['location']; ?>','<?php echo (int)$p['volume']; ?>','<?php echo (int)$p['days']; ?>','<?php echo (int)$p['price']; ?>',<?php echo ($p['featured']??false)?'true':'false'; ?>,<?php echo ($p['multi_location']??false)?'true':'false'; ?>)">Edit</button><a href="?toggle=<?php echo $p['id']; ?>" class="btn btn-outline btn-xs">Toggle</a><a href="?duplicate=<?php echo $p['id']; ?>" class="btn btn-outline btn-xs">Copy</a><a href="?delete=<?php echo $p['id']; ?>&confirm=yes" class="btn btn-danger btn-xs" onclick="return confirm('Delete?')">Del</a></div></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endif; ?>

<?php if($activeTab==='add'): ?><div class="tab-content active"><div class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="add_plan" value="1"><div class="form-grid"><div class="form-group"><label>Plan Name</label><input type="text" name="name" required></div><div class="form-group"><label>Volume (GB)</label><input type="number" name="volume" value="30" min="1"></div><div class="form-group"><label>Days</label><input type="number" name="days" value="30" min="1"></div><div class="form-group"><label>Price (Toman)</label><input type="number" name="price" value="150000" min="1000"></div></div><div class="form-group"><label style="display:flex;align-items:center;gap:10px;"><input type="checkbox" name="is_multi" value="1" onchange="document.getElementById('countrySelect').style.display=this.checked?'none':'block'" style="width:auto;accent-color:var(--t1);"> 🌍 Multi</label></div><div class="form-group" id="countrySelect"><label>Country</label><select name="location"><option value="">Select...</option><?php foreach($servers as $s): ?><option value="<?php echo $s['location']; ?>"><?php echo $s['location_emoji']??'🌍'; ?> <?php echo $s['location_name']; ?></option><?php endforeach; ?></select></div><div class="form-group"><label><input type="checkbox" name="featured" style="width:auto;"> Featured</label></div><button type="submit" class="btn btn-success" style="width:100%;">Add Plan</button></form></div></div><?php endif; ?>

<?php if($activeTab==='pending'): ?><div class="tab-content active"><div class="card"><?php if(empty($pendingList)): ?><p style="text-align:center;color:var(--text3);padding:30px;">Nothing.</p><?php else: ?><div style="overflow-x:auto;"><table><thead><tr><th>User</th><th>Plan</th><th>Amount</th><th>Receipt</th><th>Actions</th></tr></thead><tbody><?php foreach(array_reverse($pendingList) as $pp): ?><tr><td><?php echo htmlspecialchars($pp['user_name']??''); ?></td><td><?php echo htmlspecialchars($pp['plan_name']??''); ?></td><td><?php echo number_format((int)($pp['price']??0)); ?> T</td><td><?php if(!empty($pp['receipt'])): ?><a href="/data/receipts/<?php echo basename($pp['receipt']); ?>" target="_blank" class="btn btn-outline btn-xs">View</a><?php endif; ?></td><td><form method="post" action="/admin-approve.php" style="display:inline;"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="pending_id" value="<?php echo $pp['id']; ?>"><button name="action" value="approve" class="btn btn-success btn-xs">Approve</button></form> <button class="btn btn-danger btn-xs" onclick="rejectPayment('<?php echo $pp['id']; ?>')">Reject</button></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endif; ?>

<?php if($activeTab==='servers'): ?><div class="tab-content active"><div class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="save_servers" value="1"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;"><h3>Servers (<?php echo $ts; ?>)</h3><button type="button" class="btn btn-success btn-sm" onclick="addServerRow()">+ Add Server</button></div><div id="serversContainer"><?php foreach($servers as $s): ?><div class="server-row"><select name="server_flag[]" class="flag-select"><?php foreach($allFlags as $code=>$flag): ?><option value="<?php echo $flag; ?>" <?php echo ($s['location_emoji']??'')===$flag?'selected':''; ?>><?php echo $flag; ?></option><?php endforeach; ?></select><input type="text" name="server_name[]" value="<?php echo htmlspecialchars($s['location_name']); ?>" placeholder="Name"><input type="text" name="server_code[]" value="<?php echo htmlspecialchars($s['location']); ?>" placeholder="Code"><input type="text" name="server_inbounds[]" value="<?php echo implode(',',$s['inbounds']??[]); ?>" placeholder="Inbounds"><button type="button" class="btn btn-danger btn-xs" onclick="this.closest('.server-row').remove()">X</button></div><?php endforeach; ?></div><button type="submit" class="btn btn-primary" style="width:100%;margin-top:10px;">Save Servers</button></form></div></div><?php endif; ?>

<?php if($activeTab==='tests'): ?><div class="tab-content active"><div class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="save_tests" value="1"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;"><h3>Test Configs (<?php echo count($testConfigs); ?>)</h3><button type="button" class="btn btn-success btn-sm" onclick="addTestRow()">+ Add Test</button></div>
<div style="display:flex;gap:8px;margin-bottom:8px;padding:0 12px;color:var(--text3);font-size:.6rem;text-transform:uppercase"><span style="flex:2">Server</span><span style="flex:1">Vol</span><span style="flex:1">Unit</span><span style="flex:1">Hrs</span><span style="width:55px">🌍 All</span><span style="width:25px"></span></div>
<div id="testsContainer"><?php foreach($testConfigs as $tc): $isMulti=$tc['multi']??false; ?><div class="test-row"><select name="test_server[]" style="flex:2" <?php echo $isMulti?'disabled':''; ?>><?php if($isMulti): ?><input type="hidden" name="test_server[]" value="multi"><?php endif; ?>><?php foreach($servers as $s): ?><option value="<?php echo $s['location']; ?>" <?php echo ($tc['server']??'')===$s['location']?'selected':''; ?>><?php echo $s['location_emoji']??'🌍'; ?> <?php echo $s['location_name']; ?></option><?php endforeach; ?></select><input type="number" name="test_volume[]" value="<?php echo $tc['volume']??1; ?>" min="0.1" step="0.1" style="flex:1"><select name="test_unit[]" style="flex:1"><option value="GB" <?php echo ($tc['unit']??'GB')==='GB'?'selected':''; ?>>GB</option><option value="MB" <?php echo ($tc['unit']??'')==='MB'?'selected':''; ?>>MB</option></select><input type="number" name="test_hours[]" value="<?php echo $tc['hours']??2; ?>" min="1" style="flex:1"><label class="multi-check"><input type="checkbox" name="test_multi[]" value="1" <?php echo $isMulti?'checked':''; ?> onchange="this.checked?this.closest('.test-row').querySelector('select').disabled=true:this.closest('.test-row').querySelector('select').disabled=false" style="accent-color:var(--t1)"> All</label><button type="button" class="btn btn-danger btn-xs" onclick="this.closest('.test-row').remove()">X</button></div><?php endforeach; ?></div>
<?php if(empty($testConfigs)): ?><script>document.addEventListener('DOMContentLoaded',function(){addTestRow();});</script><?php endif; ?>
<button type="submit" class="btn btn-primary" style="width:100%;margin-top:10px;">Save Test Configs</button></form></div></div><?php endif; ?>

<?php if($activeTab==='users'): ?><div class="tab-content active"><div class="card"><h3 style="margin-bottom:12px">Users (<?php echo $tu; ?>)</h3><?php if(empty($allUsers)): ?><p style="text-align:center;color:var(--text3);padding:30px;">No users.</p><?php else: ?><div style="overflow-x:auto;"><table><thead><tr><th>Name</th><th>Email</th><th>Registered</th><th>Orders</th></tr></thead><tbody><?php foreach(array_reverse($allUsers) as $u): $uo=count(array_filter($orders,fn($o)=>($o['user_id']??'')===$u['id'])); ?><tr><td><?php echo htmlspecialchars($u['name']??'-'); ?></td><td><?php echo htmlspecialchars($u['email']); ?></td><td><?php echo htmlspecialchars($u['created_at']??'-'); ?></td><td><span class="badge badge-success"><?php echo $uo; ?> orders</span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endif; ?>

<?php if($activeTab==='settings'): ?><div class="tab-content active"><div class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="save_settings" value="1"><h4 style="color:var(--p1);margin-bottom:10px;">Card to Card</h4><div class="form-grid"><div class="form-group"><label>Card Number</label><input type="text" name="card_number" value="<?php echo htmlspecialchars($settings['card_number']??''); ?>"></div><div class="form-group"><label>Card Holder</label><input type="text" name="card_holder" value="<?php echo htmlspecialchars($settings['card_holder']??''); ?>"></div><div class="form-group"><label>Bank</label><input type="text" name="card_bank" value="<?php echo htmlspecialchars($settings['card_bank']??''); ?>"></div></div><h4 style="color:var(--p1);margin:14px 0 10px;">Payment</h4><div style="display:flex;gap:16px;"><label><input type="checkbox" name="zarinpal_enabled" <?php echo ($settings['zarinpal_enabled']??true)?'checked':''; ?>> Zarinpal</label><label><input type="checkbox" name="card_enabled" <?php echo ($settings['card_enabled']??true)?'checked':''; ?>> Card</label></div><button type="submit" class="btn btn-primary" style="width:100%;margin-top:14px;">Save</button></form></div></div><?php endif; ?>

<?php if($activeTab==='orders'): ?><div class="tab-content active"><div class="card"><?php if(empty($orders)): ?><p style="text-align:center;color:var(--text3);padding:30px;">No orders.</p><?php else: ?><div style="overflow-x:auto;"><table><thead><tr><th>Date</th><th>User</th><th>Product</th><th>Amount</th><th>Link</th></tr></thead><tbody><?php foreach(array_reverse($orders) as $o): ?><tr><td><?php echo htmlspecialchars($o['date']??''); ?></td><td><?php echo htmlspecialchars($o['username']??'-'); ?></td><td><?php echo htmlspecialchars($o['product']??'-'); ?></td><td><?php echo number_format((int)($o['amount']??0)); ?> T</td><td><?php if(!empty($o['subscription_url'])): ?><a href="<?php echo htmlspecialchars($o['subscription_url']); ?>" target="_blank" class="btn btn-outline btn-xs">Link</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div><?php endif; ?>

<?php if($activeTab==='panel'): ?><div class="tab-content active"><div class="card"><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="save_panel" value="1"><h4 style="color:#fdcb6e;margin-bottom:10px;">Panel Config</h4><div class="form-grid"><div class="form-group"><label>Panel URL</label><input type="text" name="panel_url" value="<?php echo PANEL_URL; ?>"></div><div class="form-group"><label>Panel Token</label><input type="text" name="panel_token" value="<?php echo PANEL_TOKEN; ?>"></div></div><div class="form-group"><label>Zarinpal Merchant ID</label><input type="text" name="merchant_id" value="<?php echo MERCHANT_ID; ?>"></div><button type="submit" class="btn btn-primary" style="width:100%;">Save</button></form></div></div><?php endif; ?>

<?php if($activeTab==='reset'): ?><div class="tab-content active"><div class="card" style="text-align:center;"><h3 style="color:var(--a1);">Reset Stats</h3><p style="color:var(--text3);font-size:.76rem;margin-bottom:14px;">Orders & pending cleared.</p><form method="post" onsubmit="return confirm('Sure?')"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="reset_stats" value="CONFIRM"><button type="submit" class="btn btn-danger" style="width:100%;">Reset</button></form></div></div><?php endif; ?>
</div>

<div class="modal-overlay" id="editModal" style="display:none;"><div class="modal"><button class="close-btn" onclick="closeEdit()">✕</button><h3>Edit Plan</h3><form method="post"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="edit_plan" value="1"><input type="hidden" name="plan_id" id="eId"><div class="form-grid"><div class="form-group"><label>Name</label><input type="text" name="name" id="eName" required></div><div class="form-group"><label>Volume</label><input type="number" name="volume" id="eVol" min="1"></div><div class="form-group"><label>Days</label><input type="number" name="days" id="eDays" min="1"></div><div class="form-group"><label>Price</label><input type="number" name="price" id="ePrice" min="1000"></div></div><div class="form-group"><label style="display:flex;align-items:center;gap:10px;"><input type="checkbox" name="is_multi" id="eIsMulti" value="1" onchange="document.getElementById('eCountrySelect').style.display=this.checked?'none':'block'" style="width:auto;accent-color:var(--t1);"> 🌍 Multi</label></div><div class="form-group" id="eCountrySelect"><label>Country</label><select name="location" id="eLoc"><?php foreach($servers as $s): ?><option value="<?php echo $s['location']; ?>"><?php echo $s['location_emoji']??'🌍'; ?> <?php echo $s['location_name']; ?></option><?php endforeach; ?></select></div><div class="form-group"><label><input type="checkbox" name="featured" id="eFeat" style="width:auto;"> Featured</label></div><div style="display:flex;gap:8px;justify-content:flex-end;"><button type="button" class="btn btn-outline" onclick="closeEdit()">Cancel</button><button type="submit" class="btn btn-primary">Save</button></div></form></div></div>
<div class="modal-overlay" id="rejectModal" style="display:none;"><div class="modal"><button class="close-btn" onclick="document.getElementById('rejectModal').style.display='none'">✕</button><h3>Reject</h3><form method="post" action="/admin-approve.php"><input type="hidden" name="csrf_token" value="<?php echo $_SESSION['csrf_token']; ?>"><input type="hidden" name="action" value="reject"><input type="hidden" name="pending_id" id="rejectPendingId"><div class="form-group"><label>Reason</label><input type="text" name="reject_reason" required></div><button type="submit" class="btn btn-danger" style="width:100%;">Submit</button></form></div></div>
<?php endif; ?>
<script>
function editPlan(id,name,loc,vol,days,price,feat,isMulti){document.getElementById('eId').value=id;document.getElementById('eName').value=name;document.getElementById('eLoc').value=loc;document.getElementById('eVol').value=vol;document.getElementById('eDays').value=days;document.getElementById('ePrice').value=price;document.getElementById('eFeat').checked=feat;document.getElementById('eIsMulti').checked=isMulti;document.getElementById('eCountrySelect').style.display=isMulti?'none':'block';document.getElementById('editModal').style.display='flex';}
function closeEdit(){document.getElementById('editModal').style.display='none';}
var em=document.getElementById('editModal');if(em)em.addEventListener('click',function(e){if(e.target===this)closeEdit();});
function rejectPayment(id){document.getElementById('rejectPendingId').value=id;document.getElementById('rejectModal').style.display='flex';}
var rm=document.getElementById('rejectModal');if(rm)rm.addEventListener('click',function(e){if(e.target===this)this.style.display='none';});
function addServerRow(){var flags=<?php echo json_encode($allFlags); ?>;var o='';for(var c in flags)o+='<option value="'+flags[c]+'">'+flags[c]+'</option>';var r=document.createElement('div');r.className='server-row';r.innerHTML='<select name="server_flag[]" class="flag-select">'+o+'</select><input type="text" name="server_name[]" placeholder="Name"><input type="text" name="server_code[]" placeholder="Code"><input type="text" name="server_inbounds[]" placeholder="Inbounds"><button type="button" class="btn btn-danger btn-xs" onclick="this.closest(\'.server-row\').remove()">X</button>';document.getElementById('serversContainer').appendChild(r);}
function addTestRow(){var opts='';<?php foreach($servers as $s): ?>opts+='<option value="<?php echo $s['location']; ?>"><?php echo $s['location_emoji']??'🌍'; ?> <?php echo $s['location_name']; ?></option>';<?php endforeach; ?>var r=document.createElement('div');r.className='test-row';r.innerHTML='<select name="test_server[]" style="flex:2">'+opts+'</select><input type="number" name="test_volume[]" value="1" min="0.1" step="0.1" style="flex:1"><select name="test_unit[]" style="flex:1"><option value="GB">GB</option><option value="MB">MB</option></select><input type="number" name="test_hours[]" value="2" min="1" style="flex:1"><label class="multi-check"><input type="checkbox" name="test_multi[]" value="1" onchange="this.checked?this.closest(\'.test-row\').querySelector(\'select\').disabled=true:this.closest(\'.test-row\').querySelector(\'select\').disabled=false" style="accent-color:var(--t1)"> All</label><button type="button" class="btn btn-danger btn-xs" onclick="this.closest(\'.test-row\').remove()">X</button>';document.getElementById('testsContainer').appendChild(r);}
setTimeout(function(){var a=document.getElementById('autoAlert');if(a)a.style.display='none';},3000);
</script>
</body></html>
